set_output:
  description: "Set the value of an output on the controller e.g. setting the lights to AUTO (Automatic) instead of using the switch entity in HA which only supports OFF/ON"
  fields:
    did:
      name: DID
      description: "DID of selected output, can be obtained from attributes of the given switch in HA"
      example: "3_1"
      selector:
        text:
    setting:
      name: Setting
      description: "Setting to set the output to e.g. ON/OFF/AUTO"
      selector:
        select:
          options:
            - "OFF"
            - "ON"
            - "AUTO"