set_output:
  description: "Set the value of an output on the controller e.g. setting the lights to AUTO (Automatic) instead of using the switch entity in HA which only supports OFF/ON"
  fields:
    did:
      name: DID
      description: "DID of selected output, can be obtained from attributes of the given switch in HA"
      example: "3_1"
      selector:
        text:
    setting:
      name: Setting
      description: "Setting to set the output to e.g. ON/OFF/AUTO"
      selector:
        select:
          options:
            - "OFF"
            - "ON"
            - "AUTO"
set_variable:
  description: "Ability to program variables on the controller e.g. Set 75 (Only Advanced mode variables supported currently!!"
  fields:
    did:
      name: DID
      description: "DID of the selected variable or output to modify"
      example: "Cntl_A1"
      selector:
        text:
    code:
      name: Code
      description: "Code to modify on the variable/output"
      example: "Set 75"
      selector:
        text:
set_dos_rate:
  description: "Set the dosing rate profile"
  fields:
    pid:
      name: PID
      description: "ID of the DOS profile"
      example: 1
      selector:
        text:
    rate:
      name: Rate
      description: "The desired dosing rate, in mL / min. (effective range is 0.1 - 83)"
      example: 1.2
      selector:
        text:
